### ISSUE TITLE
🐞 Stat block shows dice formula instead of dice icon.

### ISSUE THREAD

**Issue by Snohild** [javalent/fantasy-statblocks#391]
### Check for existing bug reports before submitting.

- [X] I searched for existing Bug Reports and found no similar reports.

### Expected Behavior

It should show a dice icon which I can click to roll attacks, damage etc. 

### Current behaviour

![image](https://github.com/javalent/fantasy-statblocks/assets/165478925/9616052a-9da7-460e-b5c6-c3e1c33f66bf)
![image](https://github.com/javalent/fantasy-statblocks/assets/165478925/ed8b9b40-4182-4571-a37e-fead297617a6)
![image](https://github.com/javalent/fantasy-statblocks/assets/165478925/645bebe3-2b92-4e0a-a892-c03b6f537080)

This happens only when I include monsters via the CLI-prosess. If I do not include monsters, and only use the included monsters in Fantasy Statblock, then it works fine. 

### Reproduction

When I first add the plugin (Fantasy Statblock + Dice Roller) everything works fine, and the stat block got its dice icon to click on. When I do the CLI-prosess to add content og and monsters, and after the index prosess, the dice icon just disappears, and it shows the dice formula text instead.

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [X] Windows

### Obsidian Version Check

1.5.12

### Plugin Version

4.1.7

### Confirmation

- [X] I have disabled all other plugins and the issue still persists.

### Possible solution

I got no idea. I have tried different config files, done the entire CLI-prosess from start to finnish numerous times, and nothing works.

**Comment by valentine195** [comment]
Can you show me the note text?

**Comment by Snohild** [comment]
From the Stat Block inside Obsidian? Or the Json.file? Or the template?

**Comment by Snohild** [comment]
![image](https://github.com/javalent/fantasy-statblocks/assets/165478925/1ebbd65b-b308-48f0-8b66-80def9cbcded)

```statblock
"name": "Goblin"
"size": "Small"
"type": "humanoid"
"subtype": "goblinoid"
"alignment": "Neutral Evil"
"ac": !!int "15"
"ac_class": "[leather armor](/3-Mechanics/CLI/items/leather-armor.md), [shield](/3-Mechanics/CLI/items/shield.md)"
"hp": !!int "7"
"hit_dice": "2d6"
"stats":
- !!int "8"
- !!int "14"
- !!int "10"
- !!int "10"
- !!int "8"
- !!int "8"
"speed": "30 ft."
"skillsaves":
  "Stealth": !!int "6"
"senses": "darkvision 60 ft., passive Perception 9"
"languages": "Common, Goblin"
"cr": "1/4"
"traits":
- "desc": "The goblin can take the Disengage or Hide action as a bonus action on each\
    \ of its turns."
  "name": "Nimble Escape"
"actions":
- "desc": "Melee Weapon Attack: dice: d20+4 (+4) to hit, reach 5 ft., one target.\
    \ Hit: dice:1d6 + 2|text(5) (1d6 + 2) slashing damage."
  "name": "Scimitar"
- "desc": "Ranged Weapon Attack: dice: d20+4 (+4) to hit, range 80/320 ft.,\
    \ one target. Hit: dice:1d6 + 2|text(5) (1d6 + 2) piercing damage."
  "name": "Shortbow"
"source":
- "MM"
- "LMoP"
- "PotA"
- "SKT"
- "TftYP"
- "ToA"
- "WDH"
- "WDMM"
- "GoS"
- "BGDIA"
- "ERLW"
- "RMBRE"
- "EGW"
- "IDRotF"
- "TCE"
- "WBtW"
- "CRCotN"
- "DSotDQ"
- "HftT"
- "PaBTSO"
- "SatO"
- "BMT"
- "GHLoE"
"image": "/3-Mechanics/CLI/bestiary/humanoid/token/goblin.webp"
```
^statblock

**Comment by Snohild** [comment]
This is by using the: *monster2md-yamlStatblock-body.txt* template.

**Comment by Snohild** [comment]
When I remove the enite CLI-folder from by Obsidian vault, the Stat Block works perfectly with the prelist of monsters which comes with Fantasy Stat Block

![image](https://github.com/javalent/fantasy-statblocks/assets/165478925/123b34f4-7be6-4c39-b254-4cba9261c5cd)

YAML:

name: Kobold
source: 5e SRD
size: Small
type: humanoid
subtype: kobold
alignment: lawful evil
ac: 12
hp: 5
hit_dice: 2d6 + -2
speed: 30 ft.
stats:
  - 7
  - 15
  - 9
  - 8
  - 7
  - 8
damage_vulnerabilities: ""
damage_resistances: ""
damage_immunities: ""
condition_immunities: ""
senses: darkvision 60 ft., passive Perception 8
languages: Common, Draconic
cr: 1/8
bestiary: true
traits:
  - name: Sunlight Sensitivity
    desc: While in sunlight, the kobold has disadvantage on attack rolls, as well as on Wisdom (Perception) checks that rely on sight.
    attack_bonus: 0
  - name: Pack Tactics
    desc: The kobold has advantage on an attack roll against a creature if at least one of the kobold's allies is within 5 ft. of the creature and the ally isn't incapacitated.
    attack_bonus: 0
actions:
  - name: Dagger
    desc: "Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 4 (1d4 + 2) piercing damage."
    attack_bonus: 4
    damage_dice: 1d4
    damage_bonus: 2
  - name: Sling
    desc: "Ranged Weapon Attack: +4 to hit, range 30/120 ft., one target. Hit: 4 (1d4 + 2) bludgeoning damage."
    attack_bonus: 4
    damage_dice: 1d4
    damage_bonus: 2
creature:
  creature:
    name: Kobold
    source: 5e SRD
    size: Small
    type: humanoid
    subtype: kobold
    alignment: lawful evil
    ac: 12
    hp: 5
    hit_dice: 2d6 + -2
    speed: 30 ft.
    stats:
      - 7
      - 15
      - 9
      - 8
      - 7
      - 8
    damage_vulnerabilities: ""
    damage_resistances: ""
    damage_immunities: ""
    condition_immunities: ""
    senses: darkvision 60 ft., passive Perception 8
    languages: Common, Draconic
    cr: 1/8
    bestiary: true
    traits:
      - name: Sunlight Sensitivity
        desc: While in sunlight, the kobold has disadvantage on attack rolls, as well as on Wisdom (Perception) checks that rely on sight.
        attack_bonus: 0
      - name: Pack Tactics
        desc: The kobold has advantage on an attack roll against a creature if at least one of the kobold's allies is within 5 ft. of the creature and the ally isn't incapacitated.
        attack_bonus: 0
    actions:
      - name: Dagger
        desc: "Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 4 (1d4 + 2) piercing damage."
        attack_bonus: 4
        damage_dice: 1d4
        damage_bonus: 2
      - name: Sling
        desc: "Ranged Weapon Attack: +4 to hit, range 30/120 ft., one target. Hit: 4 (1d4 + 2) bludgeoning damage."
        attack_bonus: 4
        damage_dice: 1d4
        damage_bonus: 2
    modifier: 2
  name: Kobold
  modifier: 0
  hp: 5
  hit_dice: 2d6 + -2
  temp: 0
  ac: 12
  current_ac: 12
  dirty_ac: false
  enabled: true
  hidden: false
  max: 5
  current_max: 5
  status: []
  initiative: 14
  static: false
  source: 5e SRD
  id: ID_695b5969d9b8
  viewing: false
  number: 0
  friendly: false
  cr: 1/8
active: false
modifier: 0
temp: 0
current_ac: 12
dirty_ac: false
enabled: true
hidden: false
max: 5
current_max: 5
status: []
initiative: 14
static: false
id: ID_695b5969d9b8
viewing: false
number: 0
friendly: false

**Comment by Snohild** [comment]
Is there a way for me to fix this now?

**Comment by Snohild** [comment]
Considering not everyone else is having this issue.

**Comment by Snohild** [comment]
Hmm, did not work:

![image](https://github.com/javalent/fantasy-statblocks/assets/165478925/9833612c-595a-418f-b2bf-bf0d566a2e60)
![image](https://github.com/javalent/fantasy-statblocks/assets/165478925/32196407-a283-45f3-bf73-a909e3bd2adc)

I restarted Obsidian, also tried to reload.

**Comment by Snohild** [comment]
![image](https://github.com/javalent/fantasy-statblocks/assets/165478925/505b19ba-de21-403f-93a0-b35aaa2a4720)

```statblock
"name": "Gnoll"
"size": "Medium"
"type": "humanoid"
"subtype": "gnoll"
"alignment": "Chaotic Evil"
"ac": !!int "15"
"ac_class": "[hide armor](/3-Mechanics/CLI/items/hide-armor.md), [shield](/3-Mechanics/CLI/items/shield.md)"
"hp": !!int "22"
"hit_dice": "5d8"
"stats":
- !!int "14"
- !!int "12"
- !!int "11"
- !!int "6"
- !!int "10"
- !!int "7"
"speed": "30 ft."
"senses": "darkvision 60 ft., passive Perception 10"
"languages": "Gnoll"
"cr": "1/2"
"traits":
- "desc": "When the gnoll reduces a creature to 0 hit points with a melee attack on\
    \ its turn, the gnoll can take a bonus action to move up to half its speed and\
    \ make a bite attack."
  "name": "Rampage"
"actions":
- "desc": "Melee Weapon Attack: dice: d20+4 (+4) to hit, reach 5 ft., one creature.\
    \ Hit: dice:1d4 + 2|text(4) (1d4 + 2) piercing damage."
  "name": "Bite"
- "desc": "Melee or Ranged Weapon Attack: dice: d20+4 (+4) to hit, reach 5 ft.\
    \ or range 20/60 ft., one target. Hit: dice:1d6 + 2|text(5) (1d6 + 2) piercing\
    \ damage, or dice:1d8 + 2|text(6) (1d8 + 2) piercing damage if used with two\
    \ hands to make a melee attack."
  "name": "Spear"
- "desc": "Ranged Weapon Attack: dice: d20+3 (+3) to hit, range 150/600 ft.,\
    \ one target. Hit: dice:1d8 + 1|text(5) (1d8 + 1) piercing damage."
  "name": "Longbow"
"source":
- "MM"
- "PotA"
- "TftYP"
- "GoS"
- "BGDIA"
- "ERLW"
- "EGW"
- "IDRotF"
- "SatO"
- "ToFW"
- "BMT"
- "DoDk"
"image": "/3-Mechanics/CLI/bestiary/humanoid/token/gnoll.webp"
```
^statblock

**Comment by valentine195** [comment]
Actually, looking at it again, it doesn’t look like the CLI emitted the code block ticks around the dice roll. So yeah, these will never render.

**Comment by Snohild** [comment]
Is there a way for me to manually fix this? I'm a bit new to this area.

**Comment by ebullient** [comment]
https://www.ebullient.dev/projects/ttrpg-convert-cli/docs/configuration.html#render-with-fantasy-statblocks

**Comment by Snohild** [comment]
Thank you SO much! I need to learn to read more through the docs.

**Comment by ebullient** [comment]
Suggestions for improvement are welcome. =)

**Comment by Snohild** [comment]
> Suggestions for improvement are welcome. =)

It makes everything work, except for the Spell Hit Modifier.

![image](https://github.com/javalent/fantasy-statblocks/assets/165478925/a147b91b-65b4-4398-9851-f4064abefa33)

**Comment by ebullient** [comment]
grumble grumble. ;)

**Comment by valentine195** [comment]
Reluctantly welcome?

**Comment by ebullient** [comment]
https://github.com/ebullient/ttrpg-convert-cli/pull/416

**Comment by Snohild** [comment]
No worries if there is no solution to it yet. It just looks a bit silly with the dice formula in the Stat Block.

**Comment by Snohild** [comment]
@ebullient With the new update, I get an error: 

C:\Users\nordm\Desktop\NY CLI\CLI-Oppdatert\5eTools\bin>ttrpg-convert.exe --index -o dm-100 -c source.json 5etools-mirror-2.github.io/data
[ Ô£à  OK] Finished reading config.
ÔÅ▒´©Å Reading C:\Users\nordm\Desktop\NY CLI\CLI-Oppdatert\5eTools\bin\5etools-mirror-2.github.io\data
[ Ô£à  OK] Finished reading data.
­ƒÆí Writing files to C:\Users\nordm\Desktop\NY CLI\CLI-Oppdatert\5eTools\bin\dm-100
[ ­ƒû╝´©Å  OK] Using C:\Users\nordm\Desktop\NY CLI\CLI-Oppdatert\5eTools\bin\5etools-img/ as the source for remote images (copyInternal=true)
[ ­ƒøæ ERR] Unable to find template for for tools5e/hazard2md.txt
[ ­ƒøæ ERR] An error occurred: Unable to render content.

**Comment by ebullient** [comment]
that's a different issue. Please hold. =)

**Comment by ebullient** [comment]
Should be fixed: https://github.com/ebullient/ttrpg-convert-cli/releases/tag/2.3.9

**Comment by BlueUser18** [comment]
I am having the same issue.  It was working before version 4.2.2, but not it is not.  I also just update CLI to version 2.3.9 and I am still not showing dice in the statblocks.  They show up in the blocks for spells but the dice do not render across the screen.
![blight](https://github.com/javalent/fantasy-statblocks/assets/20424115/f1449975-a28a-4849-9341-7c0007c3f94b)
![nezz](https://github.com/javalent/fantasy-statblocks/assets/20424115/3080684c-a611-46c3-8aa4-46150d395dfe)

**Comment by valentine195** [comment]
If you want dice to render, you need to either:
1. Globally turn it on in DR settings
2. Shift click the dice
3. have the CLI output the `|render` flag

**Comment by ebullient** [comment]
Make sure you have both of these set:

- "useDiceRoller": true
- "yamlStatblocks": true

In your picture, I still see dice formulas in your statblock, which suggests you're missing the latter of those two.

**Comment by BlueUser18** [comment]
My current CLI config

{
  "from": [
    "PHB",
	"DMG",
	"MM",
	"LMoP",
	"DIP",
	"KftGV",
	"VGM",
	"XGE"
  ],
  "paths": {
    "compendium": "6. Mechanics/CLI/",
    "rules": "6. Mechanics/CLI/rules"
  },
  "template": {
  "background": "ttrpg-convert-cli-main/examples/templates/tools5e/images-background2md.txt",
  "monster": "ttrpg-convert-cli-main/examples/templates/tools5e/monster2md-yamlStatblock-body.txt"
  },
  "useDiceRoller" : true,
  "yamlStatblocks" : true,
  "full-source": {
    "adventure": [
      "LMoP",
	  "DIP",
	  "KftGV"
    ],
    "book": [
      "PHB",
	  "DMG",
	  "MM",
	  "VGM",
	  "XGE"	  
    ]
  }
}

**Comment by BlueUser18** [comment]
> If you want dice to render, you need to either:
> 
> 1. Globally turn it on in DR settings
> 2. Shift click the dice
> 3. have the CLI output the `|render` flag

Shift click works for anything where the dice are available.
